[package]
name = "strict_json_api"
version = "0.3.3"
edition = "2024"
build = "build.rs"

[dependencies]
crabtime = { version = "1.1.2", default-features = true }
serde = { version = "1.0.219", default-features = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.140"
