[package]
name = "strict-json-api"
version = "0.1.0"
edition = "2024"

[dependencies]
crabtime = { version = "1.1.2" }
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.140"

