[package]
name = "strict_json_api"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
crabtime = { version = "1.1.2" }
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.140"

